FROM elixir:latest

RUN mkdir /app
COPY ./mdm/ /app
ADD ./big_tests/examples/ /examples/
WORKDIR /app

RUN mix local.hex --force

RUN mix do compile

ARG DOMAIN
ENV DOMAIN=${DOMAIN}
CMD iex --name pilot@${DOMAIN} --cookie ala -S mix
