FROM elixir:latest

RUN mkdir /app
COPY ./mdmminion/ /app
ADD ./big_tests/start_minion.sh /app
WORKDIR /app

RUN apt-get update && apt-get install -y \
    util-linux \
    python3 \
    ifstat \
    nethogs \
    sudo \
    psmisc \
    dnsutils \
    telnet \
    net-tools \
    vim \
    smem

RUN mix local.rebar --force
RUN mix local.hex --force
RUN mix deps.get

RUN mix do compile

ARG DOMAIN
ENV DOMAIN=${DOMAIN}
# Script checks if DOMAIN variable is empty
# If so it uses IP
CMD SHELL=/bin/sh DOMAIN=${DOMAIN} ./start_minion.sh
