# Contexts are not ./mdm or ./mdmminion because
# we have to copy example files to pilot from big_tests
# dir
version: '3'

services:
  pilot:
    build:
      context: ..
      dockerfile: ./big_tests/Dockerfile.pilot
      args:
        - DOMAIN=pilot.com
    networks:
        default:
            aliases:
                - pilot.com

    ports:
      - "4000:8080"

        #  metricsdb:
        #    image: samuelebistoletti/docker-statsd-influxdb-grafana
        #    networks:
        #        default:
        #            aliases:
        #                - mdmmetricsdb.com
        #    ports:
        #        - "3003:3003"

  minion1:
    networks:
        default:
            aliases:
                - minion1.com
    build:
      dockerfile: ./big_tests/Dockerfile.minion
      context: ..
      args:
          - DOMAIN=minion1.com
  minion2:
    networks:
        default:
            aliases:
                - minion2.com
    build:
      dockerfile: ./big_tests/Dockerfile.minion
      context: ..
      args:
          - DOMAIN=minion2.com
  minion3:
    ports:
        - "5222:5222"
    networks:
        default:
            aliases:
                - minion3.com
    build:
      dockerfile: ./big_tests/Dockerfile.minion
      context: ..
      args:
          - DOMAIN=minion3.com
