# Contexts are not ./mdm or ./mdmminion because
# we have to copy example files to pilot from big_tests
# dir
version: '3'

services:
  pilot:
    build:
      context: ..
      dockerfile: ./big_tests/Dockerfile.pilot
      args:
        - DOMAIN=pilot
    ports:
      - "4000:8080"

  minion1:
    build:
      dockerfile: ./big_tests/Dockerfile.minion
      context: ..
      args:
          - DOMAIN=minion1
  minion2:
      build:
        dockerfile: ./big_tests/Dockerfile.minion
        context: ..
        args:
            - DOMAIN=minion2
